apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: storage-demo
spec:
  containers:
    - name: nginx-pod
      image: nginx:latest
      resources:
        requests:
          cpu: "200m"
          memory: "128Mi"
        limits:
          cpu: "1"
          memory: "512Mi"
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: azure-volume
  volumes:
    - name: azure-volume
      persistentVolumeClaim:
        claimName: azurefile-pvc