apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
  namespace: storage-demo
type: Opaque
stringData:
  azurestorageaccountname: vaishnostg1218
  azurestorageaccountkey: zU+uVC9JkCGALjGBY5vWYLRDRJenbH7ZPyKlrYttsaneUWzz0Jst/cWShBHJYjiyaZIuiJ/F0lGd0A+AStDSKUEQ==