apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: rishi
  labels:
    app: nginx

spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80

    resources:
      requests:
        cpu: "200m"
        memory: "128Mi"
      limits:
        cpu: "1"
        memory: "512Mi"

    volumeMounts:
    - name: shared-volume
      mountPath: /usr/share/nginx/html

  volumes:
  - name: shared-volume
    emptyDir: 
      sizeLimit: "512Mi"