apiVersion: v1

kind: Pod

metadata:
  name: ngin-pod
  namespace: hostpath

spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
      - containerPort: 80
      resources:
        requests:
          cpu: "200m"
          memory: "512Mi"
        limits:
          cpu: "1"
          memory: "1Gi"
      volumeMounts:
        - name: hostpath-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: hostpath-volume
      hostPath:
        path: /data/nginx
        type: DirectoryOrCreate
  
  